version: '3.8' 

services:
  redis:
    image: "redis:7.2-alpine" 
    container_name: news_discovery_redis 
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data
    restart: always 
    command: redis-server --appendonly yes 
    healthcheck: 
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1 
    container_name: news_discovery_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    restart: always
    healthcheck:
      test: echo stat | nc localhost 2181 | grep Mode # Checks if ZK is running in standalone/leader/follower mode
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - news_discovery_net

  kafka:
    image: confluentinc/cp-kafka:7.2.1 # Using Confluent's Kafka image
    container_name: news_discovery_kafka
    ports:
      - "9093:9092"
      - "29092:29092"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181' 

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # This is what the container listens on internally
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093 # This one is better
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - news_discovery_net

volumes:
  redis_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:

networks: 
  news_discovery_net:
    driver: bridge
